workflows:
  android-workflow:
    name: LREC Operator Build
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Generate Gradle Wrapper
        script: |
          gradle wrapper
      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
